CREATE TABLE expenses
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by          VARCHAR(255)                            NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by          VARCHAR(255)                            NOT NULL,
    expense_date        date,
    expense_category_id BIGINT,
    amount              DECIMAL,
    details             VARCHAR(255),
    address             VARCHAR(255),
    payment_method      VARCHAR(50),
    payment_by          VARCHAR(50),
    CONSTRAINT pk_expenses PRIMARY KEY (id)
);