CREATE TABLE expense_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(50)                            NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by  VARCHAR(50)                            NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_expense_categories PRIMARY KEY (id)
);

ALTER TABLE expense_categories
    ADD CONSTRAINT uc_expense_categories_name UNIQUE (name);

ALTER TABLE expenses
    ADD CONSTRAINT fk_expense_expense_categories FOREIGN KEY (expense_category_id) REFERENCES expense_categories (id);